#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# SageMaker AI starts hosting containers with `docker run <image> serve`.
exec python /opt/serving/serve.py
